/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.mathis.stuba.router;

import javax.swing.JTable;

/**
 *
 * @author martinhudec
 */
public class RoutingTablePanel extends javax.swing.JPanel {

    /**
     * Creates new form ArpTablePanel
     */
    RouterManager manager; 
    public RoutingTablePanel(RouterManager manager) {
        initComponents();
        this.manager = manager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rootingTable = new javax.swing.JTable();
        flushTableButton = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(743, 418));

        rootingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Destination", "Netmask", "Gateway", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rootingTable);
        if (rootingTable.getColumnModel().getColumnCount() > 0) {
            rootingTable.getColumnModel().getColumn(0).setResizable(false);
            rootingTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            rootingTable.getColumnModel().getColumn(1).setResizable(false);
            rootingTable.getColumnModel().getColumn(2).setResizable(false);
            rootingTable.getColumnModel().getColumn(3).setResizable(false);
            rootingTable.getColumnModel().getColumn(4).setResizable(false);
        }

        flushTableButton.setText("Flush TABLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE))
                    .addComponent(flushTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(flushTableButton))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton flushTableButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rootingTable;
    // End of variables declaration//GEN-END:variables

    public JTable getRootingTabel() {
        return rootingTable;
    }
}
