/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.mathis.stuba.router;

import java.awt.Component;
import javax.swing.JTextField;

/**
 *
 * @author martinhudec
 */
public class StaticRoutesPanel extends javax.swing.JPanel {

    /**
     * Creates new form StaticRoutesPanel
     */
RouterManager manager; 
    public StaticRoutesPanel(RouterManager manager) {
        initComponents();
        this.manager = manager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destinationNetworkTextArea = new javax.swing.JTextField();
        netMaskTestArea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nextHopTextArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addStatic = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(743, 418));

        netMaskTestArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netMaskTestAreaActionPerformed(evt);
            }
        });

        jLabel1.setText("Destination Netwrok");

        jLabel2.setText("Network Mask");

        jLabel3.setText("Next hop");

        addStatic.setText("add route");
        addStatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaticActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextHopTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(destinationNetworkTextArea)
                    .addComponent(netMaskTestArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addStatic)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationNetworkTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(netMaskTestArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStatic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextHopTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(272, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void netMaskTestAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netMaskTestAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netMaskTestAreaActionPerformed

    private void addStaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaticActionPerformed
        manager.getRoutingTable().addStaticRoute(getDestinationNetworkTextArea().getText(), getNetMaskTestArea().getText(), getNextHopTextArea().getText(), true);
    }//GEN-LAST:event_addStaticActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStatic;
    private javax.swing.JTextField destinationNetworkTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField netMaskTestArea;
    private javax.swing.JTextField nextHopTextArea;
    // End of variables declaration//GEN-END:variables

    public JTextField getNetMaskTestArea() {
        return netMaskTestArea;
    }

    public JTextField getNextHopTextArea() {
        return nextHopTextArea;
    }

    public JTextField getDestinationNetworkTextArea() {
        return destinationNetworkTextArea;
    }
}
